### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [Petrimus/worldmustchange#2]
# Katselmointi

Terve @Petrimus! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Rekisteröin uuden käyttäjän ja kirjauduin sisään
- Testasin yhden maan visualisointia eri parametreilla
- Testasin maiden vertailujen visualisointia eri parametreilla
- Testasin listausta, filtteröintiä ja suosikkeja
- Kirjauduin ulos

### Kokemus

- Selkeä ja tyylikäs käyttöliittymä, hyvää työtä! 🥇
- Selkeät ja informatiiviset visualisoinnit, erityisen mielenkiintoista oli käyttää maita vertailevaa visualisointia
- Kätevää, että datasta on toteutettu sekä kuvaaja-, että taulukkoesitys
- Taulukkonäkymässä valittavia sivuja on enemmän kuin tuloksia. Ylimääräiset sivunumerot voisi piilottaa
- Olisi kätevää, jos sivuille voisi tehdä linkkejä, tällä hetkellä selaimen osoiterivi on koko ajan polussa `/wmc`. Esim. jos haluaisin jakaa kaverilleni Suomen ja Ruotsin päästövertailun visualiasoinnin vuodelta 2000, voisin vain jakaa linkin selaimen osoiteriviltä, kuten https://fast-bayou-83193.herokuapp.com/wmc/compare?country1=finland&country2=sweden&year=2000&type=emission

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- styled-components:in kanssa, kannattaa käyttää ulkoasun parametrisoimiseen (värit, fontit, jne.) [teema](https://styled-components.com/docs/advanced#theming)-konfiguraatiota
- Lomakkeiden tilanhallinta on hoidettu melko siististi, mutta kun lomakkeen koko kasvaa tai sen logiikka monimutkaistuu, on usein kätevää käyttää jotain lomakkeen tilanhallinnan hoitavaa kirjastoa, kuten [Formik](https://jaredpalmer.com/formik)
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- Reittien käsittelijöiden ainaisista `try { ... } catch (e) { next(e) }`-lohkoista pääsee helposti eroon [express-async-errors](https://www.npmjs.com/package/express-async-errors)-kirjaston avulla
- Kattavan näköistä backendin api:n testausta, hyvä!

## Kokonaisuus

- Erittäin mielekäs sovellus, jossa on selkeä käyttöliittymä ja informatiiviset visualisoinnit
- Koodi on kaikin puolin hyvin organisoitua ja sen sisäinen laatu on pääosin hyvässä kunnossa

**Comment by Petrimus** [comment]
Kiitos kommenteista Kalle!

Vaikka projekti on palautettu, teen omaksi ilokseni ehdottamasi muutokset sovellukseeni. Styled-componentin teema tuntui jo tekovaiheessa järkevältä, mutta se jäi vielä pois. Osoiterivin muuttamista en tullut ajatelleeksi, mutta noinhan se kannattaa tehdä varmasti tulevaisuudessakin. 

Ymmärsin oikeastaan vasta projektia tehdessäni testaamisen tärkeyden. Pienessäkin sovelluksessa on sen verran paljon liikkuvia osia, että käsin tehtävä toiminnan varmistaminen on äkkiä varsin hankalaa. Taidan ottaa tavaksi rakentaa heti testit kullekin komponentille tai modulille, ellei sitten peräti toisin päin, jolloin taidetaan mennä test driven hengessä. Näin olisi taulukon ylimääräiset sivut jäänyt pois sovelluksesta. Tässä ongelma oli se, että kun komponentti käyttää routeria ja varsinkin Reduxia, testaaminen monimutkaistui huomattavasti, jos halutaan käyttää myös Reduxin tilaa ja actioneita. Tämä jäi vielä työn alle.

Toinen havainto oli, että huolellinen suunnittelu on puoliksi tehty. Minulla oli projektissa vain pääpiirteet mitä sovellus voisi olla ja keksi tehdessä lisää. Enemmän kannattaisi pysähtyä ja luonnostella, niin tulisi kerralla oikean tai tavoitellun näköistä jälkeä.

Petri

**Comment by Kaltsoon** [comment]
> Ymmärsin oikeastaan vasta projektia tehdessäni testaamisen tärkeyden.

Hyvä kuulla!

> Tässä ongelma oli se, että kun komponentti käyttää routeria ja varsinkin Reduxia, testaaminen monimutkaistui huomattavasti, jos halutaan käyttää myös Reduxin tilaa ja actioneita

Täysin totta ja oikeastaan klassinen ongelma: mitkä tahansa ohjelman komponentit, joissa on paljon riippuvuuksia ja etenkin todella _konkreettisia_ riippuvuuksia on vaikeaa testata. Kannattaa siis tehdä todella paljon "tyhmiä" komponentteja, joissa ei sivuvaikutuksia, koska niitä on helppoa testa. Esim. tätä komponenttia on kohtuullisen vaikea testata:

```javascript
const SmartComponent = props => {
  // sivuvaikutuksia, kuten api-kutsuja, vaikeampi testata
  const apiData = useApiData();
  const reduxState = useReduxState();
  
  // paljon sivuvaikutusvapaata koodia, jota on helppo testata...
  
  return (
    // ...
  ):
}
```

Mutta, jos eristämme sivuvaikutusvapaan koodin omaksi "tyhmäksi" komponentiksi, testaaminen ja koodin luettavuus helpottuu huomattavasti:

```javascript
const DumbComponent = props => {
  // sivuvaikutusvapaata koodia, jota on helppo testata

return (
  // ...
 );
};

const SmartComponent = props => {
  // sivuvaikutuksia, kuten api-kutsuja
  const apiData = useApiData();
  const reduxState = useReduxState();
  
  return <DumpComponent data={apiData} state={reduxState}>;
}
```

Saamme nyt `DumbComponent`-komponenttia testaamalla katettua monia testiskenaarioita melko yksinkertaisilla yksikkötesteillä.

Hyvää työtä ja tsemppiä jatkokehitykseen! :)
